# Generated by Django 3.0.3 on 2020-02-23 06:42

from django.db import migrations, models
import django.db.models.deletion
import openboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.CharField(default=openboard.models.createId, max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256, null=True)),
                ('admin_auth', models.CharField(default=openboard.models.createAdminAuth, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.CharField(default=openboard.models.createId, max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256, null=True)),
                ('auth', models.CharField(default=openboard.models.createAuth, max_length=16)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openboard.Board')),
            ],
        ),
    ]
