# Generated by Django 3.0.3 on 2020-02-24 00:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import openboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('openboard', '0002_auto_20200224_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auth',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(default=openboard.models.createId, max_length=8, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openboard.Board')),
            ],
        ),
    ]
